name: TC-05 - Missing GitHub Secret

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  auth-failure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (Expected to Fail)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN1 }}
          aws-region: us-east-1

      - name: Dummy AWS Command
        run: |
          aws sts get-caller-identity

